-- Q1
SELECT
    EMP_ID,
    EMP_NAME,
    PHONE,
    HIRE_DATE,
    ENT_YN
FROM EMPLOYEE
WHERE ENT_YN = 'N'
    AND PHONE LIKE '%2'
ORDER BY HIRE_DATE DESC
LIMIT 3;

-- Q2
SELECT
    a.EMP_NAME,
    b.JOB_NAME,
    a.SALARY,
    a.EMP_ID,
    a.EMAIL,
    a.PHONE,
    a.HIRE_DATE
FROM EMPLOYEE a
JOIN JOB b ON a.JOB_CODE = b.JOB_CODE
WHERE b.JOB_NAME = '대리'
ORDER BY a.SALARY DESC ;

-- Q3
SELECT
    b.DEPT_TITLE AS '부서명',
    COUNT(a.DEPT_CODE) AS '인원',
    SUM(a.SALARY) AS '급여합계',
    AVG(a.SALARY) AS '급여평균'
FROM EMPLOYEE a
INNER JOIN DEPARTMENT b ON a.DEPT_CODE = b.DEPT_ID
WHERE ENT_YN = 'N'
GROUP BY DEPT_TITLE
WITH ROLLUP ;

-- Q4
SELECT
    a.EMP_NAME,
    a.EMP_NO,
    a.PHONE,
    b.DEPT_TITLE,
    c.JOB_NAME
FROM EMPLOYEE a
LEFT JOIN DEPARTMENT b ON a.DEPT_CODE = b.DEPT_ID
JOIN JOB c ON a.JOB_CODE = c.JOB_CODE
ORDER BY a.HIRE_DATE;

-- Q5-1
SELECT COUNT(*)
FROM EMPLOYEE
WHERE MANAGER_ID IS NOT NULL;

-- Q5-2
SELECT COUNT(*)
FROM EMPLOYEE a
JOIN EMPLOYEE b ON a.MANAGER_ID = b.EMP_ID;

-- Q5-3
SELECT a.EMP_NAME, b.EMP_NAME
FROM EMPLOYEE a
LEFT JOIN EMPLOYEE b ON a.MANAGER_ID = b.EMP_ID
ORDER BY a.EMP_NAME;

-- Q5-4
SELECT a.EMP_NAME AS '직원명',
       c.DEPT_TITLE AS '부서명',
       b.EMP_NAME AS '관리자명',
       d.DEPT_TITLE AS '관리자의 부서명'
FROM EMPLOYEE a
JOIN EMPLOYEE b ON a.MANAGER_ID = b.EMP_ID
JOIN DEPARTMENT c ON a.DEPT_CODE = c.DEPT_ID
JOIN DEPARTMENT d ON b.DEPT_CODE = d.DEPT_ID
ORDER BY a.EMP_NAME;